apiVersion: v1
kind: Service
metadata:
  name: {{ include "ddf.fullname" . }}
  labels:
    {{- include "ddf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ddf.selectorLabels" . | nindent 4 }}
